#include "AnimationMap.h"

unordered_map<Animstate, ResourceInfo> AnimStateFrameMap = {
   {PLAYER_DEFAULT, {IDB_PLAYER_DOWNWALK_IDLE, IDB_PLAYER_RIGHTWALK_IDLE, IDB_PLAYER_LEFTWALK_IDLE, IDB_PLAYER_UPWALK_IDLE}},
   {PLAYER_RIGHTWALK,{IDB_PLAYER_RIGHTWALK_IDLE, IDB_PLAYER_RIGHTWALK_ONE, IDB_PLAYER_RIGHTWALK_SECOND}},
   {PLAYER_LEFTWALK, {IDB_PLAYER_LEFTWALK_IDLE, IDB_PLAYER_LEFTWALK_ONE, IDB_PLAYER_LEFTWALK_SECOND}},
   {PLAYER_DOWNWALK, {IDB_PLAYER_DOWNWALK_IDLE, IDB_PLAYER_DOWNWALK_ONE, IDB_PLAYER_DOWNWALK_SECOND}},
   {PLAYER_UPWALK, {IDB_PLAYER_UPWALK_IDLE, IDB_PLAYER_UPWALK_ONE, IDB_PLAYER_UPWALK_SECOND}},

};