#include "AnimationMap.h"

unordered_map<Animstate, ResourceInfo> AnimStateFrameMap = {
   {PLAYER_RIGHTWALK,{IDB_PLAYER_RIGHT_IDLE, IDB_PLAYER_RIGHT_ONE, IDB_PLAYER_RIGHT_SECOND, 
					  IDB_PLAYER_RIGHT_THREE, IDB_PLAYER_RIGHT_FOUR}},
   {PLAYER_LEFTWALK, {IDB_LEFTWALK_ONE, IDB_LEFTWALK_SECOND, IDB_PLAYER_LEFTWALK_THREE, IDB_LEFTWALK_FOUR}},
   {PLAYER_DOWNWALK, {IDB_PLAYER_DOWNWALK_IDLE, IDB_PLAYER_DOWNWALK_ONE, IDB_PLAYER_DOWNWALK_SECOND, IDB_PLAYER_DOWNWALK_THREE}},
   {PLAYER_UPWALK, {IDB_PLAYER_UPWALK_IDLE, IDB_PLAYER_UPWALK_ONE, IDB_PLAYER_UPWALK_SECOND, IDB_PLAYER_UPWALK_THREE}},
   {PLAYER_USEPIKAX_RIGHT, {IDB_USEPIKAX_RIGHT_ONE, IDB_USEPIKAX_RIGHT_SECOND, IDB_USEPIKAX_RIGHT_THREE}},
   {PLAYER_USEPIKAX_LEFT, {IDB_USEPIKAX_LEFT_ONE, IDB_USEPIKAX_LEFT_SECOND}},
   {PLAYER_USEPIKAX_DOWN, {IDB_USEPIKAX_DOWN_ONE, IDB_USEPIKAX_DOWN_SECOND}},
   {PLAYER_USEPIKAX_UP, {IDB_USEPIKAX_UP_ONE, IDB_USEPIKAX_UP_SECOND}}
};